workflows:
  hello-world:
    instance_type: mac_pro
    name: Hello world workflow
    scripts:
      - until docker system info > /dev/null 2>&1; do sleep 1; done
      - cd app && docker build -t getting-started .
      - docker run -dp 3000:3000 getting-started
      - |
        docker container ls
        sleep 15
        docker container ls
